//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Astronautes
{
    //Attributs
    private int idAstronaute;
    private string nomAstronaute;
    private string prenomAstronaute;
    private int ageAstronautes;
    private static int nbAstronautes;
    //Constructeur par défaut
    public Astronautes(string nom, string prenom, int age)
    {
        nomAstronaute = nom;
        prenomAstronaute = prenom;
        ageAstronautes = age;
        nbAstronautes++;
        idAstronaute = nbAstronautes;
    }

    //Accesseurs//
	public string GetnomAstronaute
	{
        get { return nomAstronaute; }
        set { nomAstronaute = value; }
	}

    
	public string GetprenomAstronaute
	{
        get { return prenomAstronaute; }
        set { prenomAstronaute = value; }
	}
    public int GetageAstronaute
    {
        get { return ageAstronautes; }
        set { ageAstronautes = value; }
    }
 
    public int GetidAstronaute
    {
        get { return idAstronaute; }
        
    }
	//FinAccesseurs

    // Permet de comparer deux astronautes => utile dans le XML lorsqu'on sérialize les astronautes

    public override bool Equals(object obj)
    {
        Astronautes a = obj as Astronautes;

        if (a != null)
            if (this.nomAstronaute.Equals(a.nomAstronaute))
                if (this.prenomAstronaute.Equals(a.prenomAstronaute))
                    return true;
        return false;
    } 


}

