//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


public class Jour
{
    private int idJour;
    private static int nbJour = 0;
    private string etatActivite;
    private Planning PlanningJour;
    private string compteRendu;
    private List<Activités> listeActivite = new List<Activités>(); 


    //Constructeur par défaut
 
    public Jour(List<Activités> tempListeActivite, string tempCompteRendu)
    {
        nbJour++;
        listeActivite = tempListeActivite;
        idJour = nbJour;
        compteRendu = tempCompteRendu;
    }


  
    //Accesseurs//
    public string GetetatActivite
    {
        get { return etatActivite; }
        set { etatActivite = value; }
    }
    

    public List<Activités> getlisteActivite
    {
        get{return listeActivite;}
        set{listeActivite=value ;}
    }



    public int GetidJour
    {
        get { return idJour; }
        set { idJour = value; }
    }

    public string GetcompteRendu
    {
        get { return compteRendu; }
        set { compteRendu = value; }
    }

   
    //FinAccesseurs//


    // Classe de comparaison des activités
    public class ActiviteComparer : IComparer<Activités>
    {
        public int Compare(Activités x, Activités y)
        {

            return x.getHoraireDebut.CompareTo(y.getHoraireDebut);

        }
    }
	
	public void ajouterActivite(Activités nouvelleActivité)
	{
        listeActivite.Add(nouvelleActivité);
        listeActivite.Sort(new ActiviteComparer());
	}


	public virtual void supprimerActivite(int index)
	{
        listeActivite.RemoveAt(index);
	}



}

