//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Planning
{
    private List<Jour> listeDeJours;
    private DateTime dateDebut;
    private string nomPlanning;
    private static int idPlanning;
    //constructeur par défaut
    public Planning(string tempNomPlanning, List<Jour> tempListeDeJour, DateTime tempDateDebut)
    {
        nomPlanning = tempNomPlanning;
        listeDeJours = tempListeDeJour;
        dateDebut = tempDateDebut;
    }

    public Planning(string tempNomPlanning, DateTime tempDateDebut)
    {
        nomPlanning = tempNomPlanning;
        dateDebut = tempDateDebut;
    }
    //Accesseurs//
 

    public string GetnomPlanning
    {
        get { return nomPlanning; }
        set { nomPlanning = value; }
    }
    public int GetidPlanning
    {
        get { return idPlanning; }
        set { idPlanning = value; }
    }


    public DateTime GetDateDebut
    {
        get { return dateDebut; }
        set { dateDebut = value; }
    }

    //FinAccesseurs//


	public virtual int getJourActuel()
	{
        DateTime dateActuelle = new DateTime();
        dateActuelle = DateTime.Now;

        TimeSpan intervalleTemps = dateActuelle - dateDebut;
        double intervalleTempMinute = intervalleTemps.Days * 24 * 60 + intervalleTemps.Hours * 60 + intervalleTemps.Minutes;
        int numeroJourMars = (int)Math.Truncate(intervalleTempMinute /1480);
        return numeroJourMars;
	}



}

